-- Sub-routine Types catalog table — moves 65+ sub-routine types from TypeScript to database
create table public.subroutine_types (
  id uuid primary key default gen_random_uuid(),
  key text unique not null,
  label text not null,
  category text not null,
  description text not null default '',
  default_duration_min integer not null default 5,
  default_duration_max integer not null default 30,
  supports jsonb not null default '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":false}',
  student_view_description text not null default '',
  icon text not null default 'Plus',
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.subroutine_types enable row level security;
create policy "anyone_read_subroutine_types" on public.subroutine_types for select using (true);
create index idx_subroutine_types_category on public.subroutine_types(category, sort_order);

-- Seed all 65 sub-routine types
insert into public.subroutine_types (key, label, category, description, default_duration_min, default_duration_max, supports, student_view_description, icon, sort_order) values
  -- Instruction (14)
  ('mini_lesson', 'Mini-lesson', 'instruction', 'Direct instruction — teacher teaches, class participates', 10, 20, '{"assignment":true,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":true}', 'Listen and participate', 'Presentation', 1),
  ('warm_up', 'Warm-up', 'instruction', 'Quick activation — review, preview, hook, brain teaser', 3, 10, '{"assignment":true,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":true,"standards":false}', 'Quick warm-up activity', 'Zap', 2),
  ('read_aloud', 'Read Aloud', 'instruction', 'Teacher reads to the class', 10, 20, '{"assignment":true,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":true}', 'Listen to the story', 'BookOpen', 3),
  ('shared_reading', 'Shared Reading', 'instruction', 'Whole class reads a text together with stop-and-think prompts', 10, 20, '{"assignment":true,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":true,"standards":true}', 'Read together as a class', 'BookOpen', 4),
  ('video_multimedia', 'Video / Multimedia', 'instruction', 'Educational video, podcast clip, or interactive content', 5, 20, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":false}', 'Watch and learn', 'Play', 5),
  ('modeled_writing', 'Modeled Writing', 'instruction', 'Teacher writes in front of class — think-aloud demonstration', 10, 15, '{"assignment":true,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":true}', 'Watch the writing process', 'PenTool', 6),
  ('think_aloud', 'Think Aloud', 'instruction', 'Teacher verbalizes thinking process — metacognitive modeling', 5, 15, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":false}', 'Listen and observe', 'Brain', 7),
  ('vocabulary_intro', 'Vocabulary Introduction', 'instruction', 'New words introduced with definitions, context, visuals', 5, 15, '{"assignment":true,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":true,"standards":true}', 'Learn new words', 'BookA', 8),
  ('anchor_chart', 'Anchor Chart Build', 'instruction', 'Teacher builds a reference chart with the class', 5, 15, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":true}', 'Help build the chart', 'StickyNote', 9),
  ('number_talk', 'Number Talk', 'instruction', 'Mental math discussion — students share strategies', 5, 10, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":true}', 'Think and share your strategy', 'Calculator', 10),
  ('read_aloud_discussion', 'Read Aloud + Discussion Stops', 'instruction', 'Teacher reads with planned pause-and-discuss moments', 15, 25, '{"assignment":true,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":true,"standards":true}', 'Listen, stop, and discuss', 'BookOpen', 11),
  ('guest_speaker', 'Guest Speaker', 'instruction', 'Visitor presents to the class', 15, 45, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":false}', 'Listen to our guest', 'UserCheck', 12),
  ('writing_prompt', 'Writing Prompt', 'instruction', 'Teacher provides a writing prompt — students respond in writing', 10, 25, '{"assignment":true,"rubric":true,"practice_set":false,"economy_trigger":true,"submission":true,"standards":true}', 'Respond to the prompt', 'PenLine', 13),
  ('external_program', 'External Program Link', 'instruction', 'Launch an external platform — BrainPOP, Edpuzzle, Lorespark, etc.', 10, 30, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":false}', 'Open the linked program', 'ExternalLink', 14),
  -- Practice (16)
  ('independent_work', 'Independent Work', 'practice', 'Student works alone on an assigned task', 10, 40, '{"assignment":true,"rubric":true,"practice_set":false,"economy_trigger":true,"submission":true,"standards":true}', 'Work on your own', 'User', 15),
  ('partner_work', 'Partner Work', 'practice', 'Two students collaborate on a shared task', 10, 20, '{"assignment":true,"rubric":false,"practice_set":false,"economy_trigger":true,"submission":true,"standards":false}', 'Work with your partner', 'Users', 16),
  ('small_group_work', 'Small Group Work', 'practice', '3-5 students work together on a shared task', 10, 25, '{"assignment":true,"rubric":false,"practice_set":false,"economy_trigger":true,"submission":true,"standards":false}', 'Work with your group', 'UsersRound', 17),
  ('independent_reading', 'Independent Reading', 'practice', 'Silent self-selected reading — SSR, DEAR, book club', 15, 30, '{"assignment":true,"rubric":false,"practice_set":false,"economy_trigger":true,"submission":true,"standards":true}', 'Read quietly', 'BookOpen', 18),
  ('writing_time', 'Writing Time', 'practice', 'Independent drafting, revising, editing, or publishing', 15, 40, '{"assignment":true,"rubric":true,"practice_set":false,"economy_trigger":true,"submission":true,"standards":true}', 'Write independently', 'PenTool', 19),
  ('word_work', 'Word Work', 'practice', 'Phonics practice, spelling patterns, word sorts', 10, 20, '{"assignment":true,"rubric":false,"practice_set":true,"economy_trigger":true,"submission":true,"standards":true}', 'Practice your words', 'Abc', 20),
  ('fluency_practice', 'Fluency Practice', 'practice', 'Oral reading practice — partner reading, timed reading', 10, 15, '{"assignment":true,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":true,"standards":true}', 'Practice reading fluently', 'AudioLines', 21),
  ('practice_problems', 'Practice Problems', 'practice', 'Adaptive auto-scored practice from the practice engine', 5, 20, '{"assignment":false,"rubric":false,"practice_set":true,"economy_trigger":true,"submission":false,"standards":true}', 'Solve practice problems', 'Brain', 22),
  ('project_work', 'Project Work Time', 'practice', 'Students work on ongoing long-term project', 20, 45, '{"assignment":true,"rubric":true,"practice_set":false,"economy_trigger":true,"submission":true,"standards":true}', 'Work on your project', 'FolderOpen', 23),
  ('stations_centers', 'Stations / Centers', 'practice', 'Students rotate through independent learning stations', 20, 40, '{"assignment":true,"rubric":false,"practice_set":true,"economy_trigger":true,"submission":true,"standards":false}', 'Work at your station', 'LayoutGrid', 24),
  ('group_rotation', 'Group Rotation', 'practice', 'Teacher-led small group + independent stations simultaneously', 30, 60, '{"assignment":true,"rubric":true,"practice_set":true,"economy_trigger":true,"submission":true,"standards":true}', 'Work at your group''s station', 'RefreshCw', 25),
  ('homework_review', 'Homework Review', 'practice', 'Class reviews and discusses previously assigned homework', 5, 15, '{"assignment":true,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":false}', 'Review homework together', 'CheckSquare', 26),
  ('math_games', 'Math Games', 'practice', 'Math practice through structured games', 10, 20, '{"assignment":true,"rubric":false,"practice_set":true,"economy_trigger":true,"submission":false,"standards":true}', 'Play math games', 'Dice5', 27),
  ('science_investigation', 'Science Investigation / Lab', 'practice', 'Hands-on experiment, observation, data collection', 20, 45, '{"assignment":true,"rubric":true,"practice_set":false,"economy_trigger":true,"submission":true,"standards":true}', 'Investigate and discover', 'FlaskConical', 28),
  ('art_making', 'Art / Making Time', 'practice', 'Creative making, building, drawing, designing', 20, 45, '{"assignment":true,"rubric":true,"practice_set":false,"economy_trigger":false,"submission":true,"standards":false}', 'Create and make', 'Palette', 29),
  ('research_time', 'Research Time', 'practice', 'Student-directed research — reading, note-taking, sources', 15, 40, '{"assignment":true,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":true,"standards":true}', 'Research your topic', 'Search', 30),
  -- Discussion & Sharing (9)
  ('whole_class_discussion', 'Whole-Class Discussion', 'discussion_sharing', 'Structured open discussion — Socratic seminar', 10, 20, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":true}', 'Join the discussion', 'MessageSquare', 31),
  ('think_pair_share', 'Think-Pair-Share', 'discussion_sharing', 'Think then share with a partner then class', 5, 15, '{"assignment":true,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":true,"standards":false}', 'Think, then share with a partner', 'Users', 32),
  ('turn_and_talk', 'Turn and Talk', 'discussion_sharing', 'Brief partner conversation in response to a prompt', 2, 5, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":false}', 'Talk with your neighbor', 'MessageCircle', 33),
  ('share_time', 'Share Time', 'discussion_sharing', 'Students share work or ideas with the class', 5, 15, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":true,"standards":false}', 'Share your work', 'Hand', 34),
  ('student_presentation', 'Student Presentation', 'discussion_sharing', 'Students present to the class — graded by rubric', 10, 40, '{"assignment":true,"rubric":true,"practice_set":false,"economy_trigger":true,"submission":true,"standards":true}', 'Present to the class', 'Presentation', 35),
  ('class_debate', 'Class Debate', 'discussion_sharing', 'Structured argument — sides assigned, evidence required', 15, 30, '{"assignment":true,"rubric":true,"practice_set":false,"economy_trigger":false,"submission":false,"standards":true}', 'Debate your position', 'Scale', 36),
  ('gallery_walk', 'Gallery Walk', 'discussion_sharing', 'Students move around to view and respond to posted work', 10, 20, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":true,"standards":false}', 'Walk and observe', 'Eye', 37),
  ('literature_circles', 'Literature Circles / Book Clubs', 'discussion_sharing', 'Small groups discuss shared reading with assigned roles', 15, 25, '{"assignment":true,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":true,"standards":true}', 'Discuss with your book club', 'BookOpen', 38),
  ('philosophical_chairs', 'Philosophical Chairs', 'discussion_sharing', 'Students position themselves based on stance, discuss', 15, 25, '{"assignment":true,"rubric":true,"practice_set":false,"economy_trigger":false,"submission":false,"standards":true}', 'Take your position', 'Armchair', 39),
  -- Assessment (11)
  ('exit_ticket', 'Exit Ticket', 'assessment', '1-3 questions submitted at end of lesson', 3, 10, '{"assignment":true,"rubric":true,"practice_set":false,"economy_trigger":true,"submission":true,"standards":true}', 'Answer and submit', 'TicketCheck', 40),
  ('quiz', 'Quiz', 'assessment', 'Formal graded quiz — recorded in gradebook', 10, 25, '{"assignment":true,"rubric":true,"practice_set":false,"economy_trigger":true,"submission":true,"standards":true}', 'Take the quiz', 'FileQuestion', 41),
  ('test_assessment', 'Test / Unit Assessment', 'assessment', 'Formal end-of-unit assessment — IEP extended time applies', 30, 60, '{"assignment":true,"rubric":true,"practice_set":false,"economy_trigger":true,"submission":true,"standards":true}', 'Complete the assessment', 'ClipboardCheck', 42),
  ('quick_poll', 'Quick Poll / CFU', 'assessment', 'Live question to all student portals — real-time results', 2, 5, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":true,"standards":false}', 'Answer the poll', 'BarChart3', 43),
  ('self_assessment', 'Self-Assessment', 'assessment', 'Student rates their understanding 1-5 with reflection', 2, 5, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":true,"standards":false}', 'Rate your understanding', 'ThumbsUp', 44),
  ('peer_review', 'Peer Review', 'assessment', 'Students review a classmate''s work against a rubric', 10, 20, '{"assignment":true,"rubric":true,"practice_set":false,"economy_trigger":false,"submission":true,"standards":true}', 'Review a classmate''s work', 'UserCheck', 45),
  ('goal_checkin', 'Goal Check-In', 'assessment', 'Student reviews active goals and updates progress', 3, 7, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":true,"standards":false}', 'Check your goals', 'Target', 46),
  ('classwork_submission', 'Classwork Submission', 'assessment', 'Student submits completed classwork', 3, 5, '{"assignment":true,"rubric":true,"practice_set":false,"economy_trigger":true,"submission":true,"standards":true}', 'Submit your work', 'Upload', 47),
  ('observation', 'Observation / Anecdotal', 'assessment', 'Teacher observes and takes notes — no student submission', 5, 20, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":false}', 'Keep working — teacher is observing', 'Eye', 48),
  ('running_record', 'Running Record', 'assessment', 'Individual oral reading assessment — one student at a time', 10, 20, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":true}', 'Read independently while waiting', 'Mic', 49),
  ('writing_conference', 'Writing Conference', 'assessment', 'Teacher meets 1:1 about writing while class writes', 20, 40, '{"assignment":true,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":true,"standards":true}', 'Write — teacher will come to you', 'PenTool', 50),
  -- Routine (6)
  ('brain_break', 'Brain Break', 'routine', 'Short movement or sensory reset to restore focus', 2, 5, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":false}', 'Time for a brain break!', 'Zap', 51),
  ('transition_routine', 'Transition', 'routine', 'Students move, get materials, or shift activities', 1, 5, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":false}', 'Get ready for the next activity', 'ArrowRightLeft', 52),
  ('mindfulness_moment', 'Mindfulness / Breathing', 'routine', 'Guided breathing, gratitude, quiet reflection', 2, 5, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":false}', 'Breathe and relax', 'Flower2', 53),
  ('clean_up', 'Clean-up', 'routine', 'End-of-activity tidy — materials away, area reset', 2, 5, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":false}', 'Clean up your area', 'Trash2', 54),
  ('materials_distribution', 'Materials Distribution', 'routine', 'Handing out papers, books, or supplies', 1, 3, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":false}', 'Get your materials ready', 'Package', 55),
  ('lining_up', 'Lining Up / Dismissal Prep', 'routine', 'Students pack up, line up, or prepare to leave', 2, 5, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":false}', 'Get ready to go', 'DoorOpen', 56),
  -- Economy (6)
  ('coin_award', 'Coin Award', 'economy', 'Teacher awards coins to individuals or whole class', 2, 5, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":true,"submission":false,"standards":false}', 'Coins incoming!', 'Coins', 57),
  ('class_store_moment', 'Class Store Moment', 'economy', 'Brief window for students to browse and spend coins', 5, 10, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":false}', 'Browse the class store', 'ShoppingBag', 58),
  ('mystery_reveal', 'Mystery Student Reveal', 'economy', 'End-of-day reveal of mystery student — fires on all portals', 3, 5, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":true,"submission":false,"standards":false}', 'Who is the mystery student?', 'HelpCircle', 59),
  ('mystery_motivator', 'Mystery Motivator Check', 'economy', 'Update class-wide progress bar toward hidden reward', 2, 3, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":false}', 'How close are we?', 'Gift', 60),
  ('job_rotation', 'Job Rotation Announcement', 'economy', 'Announce new class job assignments', 2, 3, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":false,"submission":false,"standards":false}', 'New jobs are here!', 'BadgeCheck', 61),
  ('seating_auction', 'Seating Auction', 'economy', 'Students spend coins to claim premium seats', 3, 5, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":true,"submission":false,"standards":false}', 'Bid on your seat!', 'Armchair', 62),
  -- Special (4)
  ('group_rotation_full', 'Group Rotation (Station Builder)', 'special', 'Full station builder — teacher configures stations, assigns groups', 20, 60, '{"assignment":true,"rubric":true,"practice_set":true,"economy_trigger":true,"submission":true,"standards":true}', 'Work at your group''s station', 'RefreshCw', 63),
  ('peer_tutoring', 'Peer Tutoring Session', 'special', 'Teacher-approved peer pairs — mastery student tutors developing student', 10, 20, '{"assignment":false,"rubric":false,"practice_set":true,"economy_trigger":true,"submission":false,"standards":true}', 'Help and learn together', 'Handshake', 64),
  ('time_capsule', 'Time Capsule', 'special', 'Students write a letter to future selves — sealed until year end', 15, 30, '{"assignment":false,"rubric":false,"practice_set":false,"economy_trigger":true,"submission":true,"standards":false}', 'Write to your future self', 'Clock', 65),
  ('custom_subroutine', 'Custom Sub-routine', 'special', 'Teacher names it anything, sets duration, attaches any properties', 5, 30, '{"assignment":true,"rubric":true,"practice_set":true,"economy_trigger":true,"submission":true,"standards":true}', '', 'Plus', 66)
on conflict (key) do nothing;
